# Generated by Django 4.0 on 2021-12-27 01:28

from django.db import migrations, models
import django.db.models.deletion
import war.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('licence', models.CharField(blank=True, default='All Rights Reserved.', max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('weekday', models.IntegerField(choices=[(1, 'Mon'), (2, 'Tues'), (3, 'Wednes'), (4, 'Thurs'), (5, 'Fri'), (6, 'Satur'), (7, 'Sun')], db_index=True, default=war.models.Weekday.today, editable=False)),
                ('repetition', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')], db_index=True, default=war.models.Repetition.today, editable=False)),
                ('month', models.IntegerField(choices=[(1, 'July'), (2, 'August'), (3, 'Septem'), (4, 'Octo'), (5, 'Novem'), (6, 'Decem'), (7, 'Janu'), (8, 'Febru'), (9, 'March'), (10, 'April'), (11, 'May'), (12, 'June')], db_index=True, default=war.models.Month.today, editable=False)),
                ('entry', models.TextField()),
                ('title', models.CharField(blank=True, max_length=150)),
                ('modified_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sire', to='post.entry')),
                ('warnings', models.ManyToManyField(blank=True, null=True, to='post.CW')),
            ],
        ),
    ]
